# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f42149707859d11229bb45695665dd86e3a18b04858b2ce3a6a745a77539ab8d8ba5af6928ac09c2781ecddf256738d5fa46408b35dc417781ea35d7f2c28d2

test:
  secret_key_base: 0abc7374c9a8ada276a26b96f90ae3ce42cb16a9b8e26424500d6db017a424fe543e850a7abf474da47620b7e9ca6f32232ac5700de851d185a43fcd2b154832

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
